### ISSUE TITLE
Filter converts elements to native type?

### ISSUE THREAD

**Issue by djMax** [LegendApp/legend-state#94] opened 2023-01-27 16:52 UTC
I have a state like this: 

```
function defaultBoard() { return { black: [new Piece(), new Piece()], white: [new Piece(), new Piece()] }; }
export const GameState = observable({
  board: defaultBoard(),
});
```

And then I iterate over it like this:
```
  const takes = GameState.black.filter(
    (p) => checkSomeStuff(),
  );
```

The compiler (and I) expect that takes is an array of Observables, but we are both mistaken, it is an array of Pieces. Is this expected?

**Comment by jmeistrich** [comment] 2023-02-01 23:18
@djMax That's strange. There's specifically an override for array loopers like `filter` to pass in the observable. I just added a test to confirm and it looks to be working correctly.

Can you share a larger code sample that I could test?

**Comment by djMax** [comment] 2023-02-02 02:00
I will try to isolate it to something simple. I didn't really have the tao of peek vs get, so after cleaning all that up, the use case kind of went away, but I can try to reconstruct.

**Comment by jmeistrich** [comment] 2023-02-23 12:15
I'm going to close this since it seems like a no-repro, but please reopen it if you can reproduce the bug.

**Closed by jmeistrich** 2023-02-23 12:15 UTC

**Comment by shamilovtim** [comment] 2023-05-13 01:19
I encountered the same issue with `array.find()` the element returned from it is not an Observable<MyType>. is that intended @jmeistrich?

**Comment by shamilovtim** [comment] 2023-05-13 01:29
See the type hint in my screengrab: 
<img width="507" alt="Screenshot 2023-05-12 at 9 29 06 PM" src="https://github.com/LegendApp/legend-state/assets/3495974/e26e2ddd-5b68-456b-b679-02033efc71c4">
