### ISSUE TITLE
Weird experience with persistence

### ISSUE THREAD

**Issue by olup** [LegendApp/legend-state#181] opened 2023-08-18 20:37 UTC
I try to persist one of my state keys, an object containing different data, in my local storage.

When I start my app there is no initial writing to the (empty) local storage - only when I actually make a change to the initiated state can I see a chnage in my localStorage.

Usually, my first interaction with the state is setting a new key to an object with a string id as key and another object as value (it's an index)

Only those changes are written to localstorage, and so my app is not getting the full picture when refreshing.

That does not seem like expected behavior, am I missing something ?

**Comment by jmeistrich** [comment] 2023-08-19 05:02
That is the expected behavior - it only persists changes after it's created. And on load the changes are merged into the existing data. The reasoning is that we can create the observable with some default data, and then they are overridden by the persisted data if they changed.

Are you wanting it to save its current state when `persistObservable` is called? I'm curious what the use case is for that - is the observable being populated from another data source first? Can you `persistObservable` earlier so that the other data comes in after it's created and is considered a change?

**Comment by olup** [comment] 2023-08-19 05:31
I understand. On the other hand it feels expectable that if I create a state with some data, it's part of my state and should probably be persisted.

As for populating the state after the creation of the persisting mechanism, I tried it but did not find it straightforward:

The main problem is that I need to populate the state on creation to satisfy the typing - but if I then re populate the state with the same values (with a global set() on the state, using a deeply copied version of the default state I keep around) then most of the state don't change, and thus is not persisted - at least that's what I am observing.

I could initiate the state with wrong or dumb values, to be overriden later on, but it feels very hacky.

I had hope with the "sync" method of the persistence observable, but that only syncs from storage to memory I believe.

**Comment by jmeistrich** [comment] 2023-08-21 08:53
Can you share what your initial state looks like? I'm not quite understanding the issue - if you have some initial data in the observable and load it from persistence, it should merge the persisted changes on top of the defaults. So even if only a single changed field is persisted, once loaded it should be the full initial state plus that one change merged in. Is that not leaving in the state you expect? Or are you needing to examine the data in storage?

For what it's worth with the typing issue, this is a bit of what our state looks like:
```ts
auth: {
    uid: '',
    email: '',
},
temp: {
    hadError: false,
    isOnline: false,
    toasts: {} as Record<string, ToastInfo>,
    pageRedirectedToLogin: '',
    showWalkthroughs: false,
    alert: undefined as AlertInfo,
    confirm: undefined as ConfirmInfo,
    addClient: undefined as ClientInviteModalType
}
```

So it is typed correctly but using `as` to be able to use undefined or {} when not actually loaded yet.

**Comment by jmeistrich** [comment] 2023-09-05 17:41
I'm going to close this due to lack of response. @olup feel free to reopen it if you think this should change.

**Closed by jmeistrich** 2023-09-05 17:41 UTC

**Comment by fbinz** [comment] 2024-05-20 17:35
I think I ran into the same issue. 

I'm working on a react-native application, where I want to generate (preliminary) user IDs on the client side.
Basically, I'm doing this:
```js
import { randomUUID } from "expo-crypto";

configureObservablePersistence({
  pluginLocal: ObservablePersistMMKV,
});

export const user$ = observable({
  id: randomUUID(),
});

persistObservable(user$, { local: "user" });
```

My expectation was, that this would generate a random UUID once and then on subsequent runs, get the value from MMKV. Instead, the user ID changes for every run.

Instead, I'm now doing this:
```js
import { randomUUID } from "expo-crypto";

configureObservablePersistence({
  // Use react-native-mmkv in React Native
  pluginLocal: ObservablePersistMMKV,
});

export const user$ = observable({
  id: "",
});

persistObservable(user$, { local: "user" });

observe(() => {
  if (user$.id.get() === "") {
    user$.id.set(randomUUID());
  }
});
```

Is this the "correct" or intended way, to implement this?

**Comment by jmeistrich** [comment] 2024-05-21 03:38
Yes, that’s the intended way, but I think you don’t need the observe. Because mmkv loads synchronously, it should already have the value loaded immediately after calling persistObservable. But that might be safer to keep it there anyway :)

**Comment by fbinz** [comment] 2024-05-22 15:47
Thanks for the swift answer. :)
I see, so you mean just do this:

```js
import { randomUUID } from "expo-crypto";

configureObservablePersistence({
  pluginLocal: ObservablePersistMMKV,
});

export const user$ = observable({
  id: "",
});

persistObservable(user$, { local: "user" });

if (user$.id.get() === "") {
  user$.id.set(randomUUID());
}
```

If that works, that would be refreshingly simple. :D
