### ISSUE TITLE
Observe doesn't get triggered for computed value more than once

### ISSUE THREAD

**Issue by sergeylaptev** [LegendApp/legend-state#241] opened 2024-01-31 00:56 UTC
I recently started using this library and encountered strange behavior in the process. Here's an example of a test state, nothing special:
```ts
const stateTest$: ObservableObject<StateTest> = observable<StateTest>({
  id: '1',
  items: [{ id: '1' }, { id: '2' }, { id: '3' }],
  selectedItem: computed(() => {
    console.log('Computing for ID: %s', stateTest$.id.get())

    const item = stateTest$.items.find(
      (_item) => _item.id.peek() === stateTest$.id.get(),
    )

    console.log('Next Selected item: ', item)

    return item
  }),
})
```

Every time I start observing for changes in the computed value of `selectedItem`, the function is called only once.

```ts
observe(() => {
  console.log('Observed Selected Item: ', stateTest$.selectedItem.get())
})

setTimeout(() => {
  stateTest$.id.set('2')
}, 2000)

setTimeout(() => {
  stateTest$.id.set('3')
}, 10000)
```

The log is:
```
Computing for ID: 1
Next Selected item:  {"id": {}}
Observed Selected Item:  {"id": "1"}
Computing for ID: 2
Next Selected item:  {"id": {}}
Computing for ID: 3
Next Selected item:  {"id": {}}
```

As soon as I start listening to non-computed state fields, observing works correctly again:

```ts
observe(() => {
  console.log('Observed Selected Item: %s', stateTest$.selectedItem.get())
  console.log('Observed ID: %s', stateTest$.id.get())
})
```

The log is:
```
Computing for ID: 1
Next Selected item:  {"id": {}}
Observed Selected Item: {"id": "1"}
Observed ID: 1
Computing for ID: 2
Next Selected item:  {"id": {}}
Observed Selected Item: {"id": "2"}
Observed ID: 2
Computing for ID: 3
Next Selected item:  {"id": {}}
Observed Selected Item: {"id": "3"}
Observed ID: 3
```

The same is true if I simply refer a computed field without getting a value.
```ts
observe(() => {
  console.log('Observed Selected Item: ', stateTest$.selectedItem)
})
```

The log is:
```
Computing for ID: 1
Next Selected item:  {"id": {}}
Observed Selected Item: {}
Computing for ID: 2
Next Selected item:  {"id": {}}
Observed Selected Item: {}
Computing for ID: 3
Next Selected item:  {"id": {}}
Observed Selected Item: {}
```

**Comment by jmeistrich** [comment] 2024-02-02 17:52
I think the issue is that the `find` is running on the observable and returning an observable, so the computed is actually linking to a different observable. I think what you want is to return the actual object?

So just a small tweak should work. `get()` the value of `items` before calling `find` on it:

```js
const item = stateTest$.items.get().find((_item) => _item.id === stateTest$.id.get());
```

Is that what you're looking for?

**Comment by KycKyc** [comment] 2024-02-02 23:42
@jmeistrich we kinda thought about using it as linked observable.
Like, simplified case, let's define a state:
```
const stateTest$: ObservableObject<StateTest> = observable<StateTest>({
    id: '1',
    items: [
        { id: '1', price: 10 },
        { id: '2', price: 10 },
        { id: '3', price: 10 },
    ],
    selectedItem: computed(() => {
        return stateTest$.items.find((_item) => _item.id.peek() === stateTest$.id.get());
    }),
});

```

And react component:
```
export const ItemComponent = observer(()=>{
    return (
    <div>
        <div>Item Price:</div>
        <div>
            <Memo>{() => <div>{state$.selectedItem.get()?.price}</div>}</Memo>
        </div>
    </div>
    )
})

```

And somewhere we have a code, that will update a price, maybe we got an update via websockets, let's emulate it like this:
```
setTimeout(() => {
    stateTest$.items[0].price.set(40);
}, 6000);
```

If we will return just an object from `computed`, we will lose an ability to update price, cause we are not tracking changes inside object now.
If we will return observable from `computed`, we will not be able to switch current active item, like `stateTest$.id.set('2')` will not trigger component update, since it's only tracking updates inside linked observable.

We can remove `computed`, but then we will have to write something like (if we want to utilize fine grained reactivity):
```
export const ItemComponent = observer(()=>{
    return (
    <div>
        <div>Item Price:</div>
        <div>
                <Memo>
                    {() => {
                        const selected = state$.items.find((item) => item.id.peek() === state$.id.get());
                        return <div>{selected?.price.get()}</div>;
                    }}
                </Memo>
        </div>
    </div>
    )
})
```

And if we will add more props to `Item` we will have to repeat the same <Memo> section with `find` inside....
Because looks like, we can't do:
```
export const ItemComponent = observer(()=>{
    const selected = state$.items.find((item) => item.id.peek() === state$.id.get());
    return (
    <div>
        <div>Item Price:</div>
        <div>
                <Memo>
                    {() => {
                        return <div>{selected?.price.get()}</div>;
                    }}
                </Memo>
        </div>
    </div>
    )
})
```
It will just not render anything.

**Comment by jmeistrich** [comment] 2024-02-03 10:25
Ah ok, I understand now. Thanks for all of the details!

I'm actually in the middle of a big rewrite of `computed` right now, to make it more powerful to do things like this and also be easier to use. This is one of the things I'm trying to solve and I have a failing test for it.

The problem is that `state$.selectedItem.get()` is calling `get()` directly on the target observable, and so it never actually observes the computed. I need to figure out how to track all computeds up the hierarchy without adding a lot of overhead of checking the entire hierarchy in every single `get` call.

The way we work around this in the meantime is to specifically track the `id` as well. That will make it re-render whenever the selected id changes as well as whenever the data in the target selected item changes.

```js
export const ItemComponent = observer(()=>{
    return (
    <div>
        <div>Item Price:</div>
        <div>
            <Memo>{() => <div>{state$.id.get() && state$.selectedItem.get()?.price}</div>}</Memo>
        </div>
    </div>
    )
})
```

**Comment by jmeistrich** [comment] 2024-02-17 21:54
I've got this fixed in version `2.2.0-next.35` which will turn into a beta version 3.0 within the next few weeks. I'll leave this open until that is released and documented :).

**Comment by mkhennoussi** [comment] 2024-02-18 22:19
Yes ! Perfect timing, I was on this issue for the last couple hours ! Works great on `2.2.0-next.35` ! Thanks a lot for your work and this amazing lib @jmeistrich !

**Comment by jmeistrich** [comment] 2024-02-18 22:45
Very happy to hear it @mkhennoussi! Are you already using the @next version in your app? I hope that's not causing too much trouble since the changes aren't documented yet. The existing features should be mostly the same except that `computed` will be deprecated because now child functions just become computeds. So the original example will just have `computed` removed and now look like:

```ts
const stateTest$: ObservableObject<StateTest> = observable<StateTest>({
  id: '1',
  items: [{ id: '1' }, { id: '2' }, { id: '3' }],
  selectedItem: () => {
    console.log('Computing for ID: %s', stateTest$.id.get())

    const item = stateTest$.items.find(
      (_item) => _item.id.peek() === stateTest$.id.get(),
    )

    console.log('Next Selected item: ', item)

    return item
  }
})
```

And to create a computed you can just use `observable`:
```js
// before
const comp$ = computed(() => state$.value.get())
// after
const comp$ = observable(() => state$.value.get())
```

In the current @next version, the old `computed` is currently still there unchanged and won't have most of the improvements, but I'm planning to change it to a simple wrapper around the new stuff in the final release.

And I just released `2.2.0-next.37` which cleans up some rough edges.

**Comment by mkhennoussi** [comment] 2024-02-18 23:05
Yes I've just started to use the `next` version as I needed a way to get a "sub tree of the state" to make the work with some "selected" items easier. Love the simplicity we have now. Things just work and feel natural 💪👌. Congrats !

**Comment by mkhennoussi** [comment] 2024-02-19 00:20
One thing I have noticed is that imagine with have the following state (with players inside teams), it seems we can't make `computed` values from the selected team and using it inside the selected player ? : 
```typescript
const stateTest$: ObservableObject<StateTest> = observable<StateTest>({
  teams: [{ id: 'team1', players: [{id: 'player1'}, {id: 'player2'}] }, { id: 'team2', players: [{id: 'player3'}, {id: 'player4'}] }],
  selectedTeamId: "",
  selectedTeam: () => {
    const team= stateTest$.teams.find(
      (_team) => _team.id.peek() === stateTest$.selectedTeamId.get()
    )
    return team;
  },
  selectedPlayerId: "",
  selectedPlayer: () => {
   const player = stateTest$.selectedTeam.find(
        (_player) => _player.id.peek() === stateTest$.selectedPlayerId.get(),
   )
   return player
  }
})
```

Thanks !

**Comment by jmeistrich** [comment] 2024-02-19 01:54
That should work. Is it not working? Can you share a code sample I can run which shows how it's failing?

**Closed** 2024-05-22 19:48 UTC
