### ISSUE TITLE
Proxy trap returned false for property

### ISSUE THREAD

**Issue by devotox** [LegendApp/legend-state#129] opened 2023-06-15 13:37 UTC
This seems to happen when

### Create a computed that is listening to 2 keys in same object
```
computed(() => {
	const { isLoading, transactions } = getTransactions();

	return {
		isLoading: isLoading.get(),
		transactions: transactions.get()
	}
})
```

### Change the values for both at the same time
```
	observable.assign({ isLoading: false, transactions: [...array] });
```

You will notice that the computed runs twice even though i would expect it to run once and batched
and then this error occurs `Proxy trap returned false for property`

**Comment by jmeistrich** [comment] 2023-06-15 17:21
Can you share a full example that I can test with? I tried with my guess as to what you're doing and it works correctly.

```js
const obs = observable({ isLoading: false, transactions: [] });
const a = computed(() => {
    return {
        isLoading: obs.isLoading.get(),
        transactions: obs.transactions.get(),
    };
});

obs.assign({ isLoading: false, transactions: [0] });
```

**Comment by devotox** [comment] 2023-06-16 08:12
I can't share the exact example as it is from a private companies codebase but we have connected https://tanstack.com/query/v4 to legend-state and what may be happening is that it emits both these events one after the other semi quickly. i.e. it first emits the new transactions array from empty to some data and then it emits again that isLoading has changed and thus the computed gets 2 changes very quickly rather than just 1.

Does that make sense?

**Comment by jmeistrich** [comment] 2023-06-16 08:20
There shouldn't be any problem with quick events. I've never seen that "Proxy trap" error before. Can you create an example that reproduces the error in the company code? I don't have enough information to try to track down a possible bug.

The computed running twice is expected - computed ignores batching and recomputes immediately so that it will have the correct value if accessed during the batch. But it just doesn't notify its listeners until the end of the batch. It could potentially be more efficient to mark it dirty and recompute when accessed or at the end of the batch, but that would be more complex and the computations themselves shouldn't be too expensive. We may revisit that and optimize it in a later update.

**Comment by devotox** [comment] 2023-06-16 15:34
```
TypeError: Proxy trap returned false for property\n   
   at assign .assign (native undefined)\n   
   at assign .assign (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.shares.app.dev:180954:20 undefined)\n   
   at anonymous .anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.shares.app.dev:180789:24 undefined)\n   
   at assignResponse .assignResponse (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.shares.app.dev:190047:33 undefined)\n   
   at finalizeObservable .finalizeObservable (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.shares.app.dev:190028:28 undefined)\n   
   ```

**Comment by devotox** [comment] 2023-06-16 15:48
also as soon as i wrapped the `observable.assign` in `setImmediate` no more issues

**Comment by jmeistrich** [comment] 2023-06-16 19:05
If you can just show a snippet of real code I could help, even if you can't make a full repro. For example `observable.assign` wouldn't actually work but I'm guessing you're calling assign on an observable object? 

Are you trying to assign to the computed? That wouldn't work because it's read-only but it should show a more helpful error message.

It's also possible it's completely unrelated to legend-state... I don't recognize `finalizeObservable` or `assignResponse`. Are those functions in your code or do you have another observable library? Or maybe it's a crash in another proxy in your code?

**Comment by devotox** [comment] 2023-06-16 21:33
// Model.ts - abstract class
```
  /**
   * Convert data from react-query into a legendState observable
   *
   * @private
   * @param modelObservable
   * @param options
   * @param result
   */
  private finalizeObservable<K extends unknown = unknown>(
    modelObservable: ModelObservable<K>,
    options: AllQueryMutationOptions<K>,
    result?: AllQueryMutationObserverResult<K>,
  ): ModelObservable<K> {
    let response = {} as Partial<ModelObservableValue<K>>;

    if (isInfiniteQueryOptions(options)) {
      const observer = modelObservable.peek().observer as InfiniteQueryObserver<K>;
      const defaultedOptions = queryClient.defaultQueryOptions(options);
      const { data } = observer.getOptimisticResult(defaultedOptions);
      !result && (result = observer.getCurrentResult());

      response.data = lastPage(data) as NonNullable<K>;
      response.infiniteData = flattenPages(data) as NonNullable<K>;
      response.infiniteDataPaged = data as NonNullable<InfiniteData<K>>;
    }

    if (isQueryOptions(options)) {
      const observer = modelObservable.peek().observer as QueryObserver<K>;
      const defaultedOptions = queryClient.defaultQueryOptions(options);
      const { data } = observer.getOptimisticResult(defaultedOptions);
      !result && (result = observer.getCurrentResult());
      observer.setOptions(defaultedOptions);
      response.data = data as NonNullable<K>;
    }

    response = this.defaultObservableValue<K>(result, response);

    if (result && isInfiniteQueryResult(result)) {
      Object.assign(response, {
        data: lastPage(result.data),
        infiniteDataPaged: result.data,
        infiniteData: flattenPages(result.data),
      });
    }

    this.assignResponse(modelObservable, response);
    return modelObservable;
  }


  /**
   * Do not update response if all keys are equal
   */
  private assignResponse<K>(
    modelObservable: ModelObservable<K>,
    response: Partial<ModelObservableValue<K>>,
  ): void {
    try {
      modelObservable.assign(response);
    } catch (err) {
      const error = err as Error;
      const className = this.constructor.name;
      reportError(`Error in ${className} observable assign`, {
        message: `${error.message} in ${className} Model`,
        stack: error.stack,
        observableDiff,
      });
    }
  }

  /**
   * Merge react-query values with
   * default values for the legendState observable
   *
   * @private
   * @param [result]
   * @param [response]
   */
  private defaultObservableValue<K>(
    result?: AllQueryMutationObserverResult<K>,
    response?: Partial<ModelObservableValue<K>>,
  ): Partial<ModelObservableValue<K>> {
    const defaults = {
      // data: undefined, // do not set data here as it will cause proxy trap error
      // infiniteData: undefined, // do not set data here as it will cause proxy trap error
      // infiniteDataPaged: undefined, // do not set data here as it will cause proxy trap error
      error: null,
      isStale: false,
      isError: false,
      isPaused: false,
      isSuccess: false,
      isLoading: false,
      isFetched: false,
      isFetching: false,
      isRefetching: false,
      dataUpdatedAt: null,
      hasNextPage: false,
      hasPreviousPage: false,
      isFetchingNextPage: false,
      isFetchingPreviousPage: false,
      refetch: noop,
      reset: noopSync,
      remove: noopSync,
      fetchNextPage: noop,
      fetchPreviousPage: noop,
    };

    type DefaultKey = keyof typeof defaults;
    const defaultKeys = Object.keys(defaults) as DefaultKey[];
    const res = Object.assign({}, defaults, response, result);

    Object.keys(res).forEach(
      (key) => !defaultKeys.includes(key as DefaultKey) && Reflect.deleteProperty(res, key),
    );

    return Object.assign(res, {
      data: result?.data || response?.data,
    }) as Partial<ModelObservableValue<K>>;
  }
  
    /**
   * Caches computed observables
   *
   * @protected
   * @param computeKey
   * @param fn
   */
  protected computed<K>(computeKey: string, fn: () => K): ObservableComputed<K> {
    const cacheKey = this.createQueryKeyString({ type: 'computed', computeKey });
    const cachedComputed = this.computeStore.get(cacheKey);

    if (cachedComputed) {
      return cachedComputed;
    }

    const computedFn = computed(fn);
    this.computeStore.set(cacheKey, computedFn);
    return computedFn;
  }

  private batch(fn: () => unknown): void {
    batch(() => {
      try {
        fn();
      } catch (err) {
        const error = err as Error;
        const className = this.constructor.name;
        reportError(`Error in ${className} observable batch`, {
          message: `${error.message} in ${className} Model`,
          stack: error.stack,
        });
      }
    });
  }
```


Portfolio.model.ts
```
  getAllTransactions() {
    return this.computed('AllTransactions', () => {
      const { infiniteData, fetchNextPage, isLoading: _isLoading } = this.getTransactions();

      const transactions = infiniteData
        ?.get()
        ?.filter((value, index, self) => index === self.findIndex((t) => t?.id === value?.id));

      const isLoading = _isLoading.get();
      const hasTransactions = !isLoading && transactions?.length > 0;

      return {
        isLoading,
        transactions,
        fetchNextPage,
        hasTransactions,
      };
    });
  }

```


The issue occurs when when `isLoading.get()` runs if i change to `.peek` then there is no issue

**Comment by jmeistrich** [comment] 2023-06-16 22:15
Hmm, I don't know why an extra `get()` in a computed would cause a proxy trap error... That error should occur when setting an observable directly, like if you `obs.isLoading = true` or `Object.assign(obs, value)`. But unless I'm reading it wrong I don't see anything like that in there.

I just released a new version 1.2.9 that adds logging when it returns false in the proxy trap that might provide more information to you, and you could put a breakpoint there to see where that's happening. 

Maybe there's a circular dependency on the computed that's assigning directly to an observable?

**Comment by chakrihacker** [comment] 2023-06-17 06:01
I also faced this, but couldn't get a proper reproduction will see if I can do it too

**Comment by devotox** [comment] 2023-06-17 12:52
The issue definitely occurs when the `obs.assign` happens but the only way it seems to trigger in this instance is when i had an extra `.get` mind you i have many other places i have used many `.get` and it has worked so its not exactly pertaining to that but it seems there is some kind of race condition somewhere

**Comment by devotox** [comment] 2023-06-17 18:53
```
  ● portfolioChartSection › chart have the correct props - user have buy transactions

    TypeError: 'set' on proxy: trap returned falsish for property '1'
        at Function.assign (<anonymous>)

      79 |         obs.assign({ data });
      80 |         obs.assign(observableOptions);
    > 81 |         obs.infiniteData.assign(infiniteData);
         |                          ^
      82 |         obs.infiniteDataPaged.assign(infiniteDataPaged);
```

**Comment by devotox** [comment] 2023-06-17 18:53
Updating to this fixed it

```
 obs.assign({ data });
        obs.assign({ infiniteData });
        obs.assign({ infiniteDataPaged });
        obs.assign({ ...observableOptions });
        ```

**Comment by jmeistrich** [comment] 2023-06-17 19:57
Ok awesome, that helped me figure out the problem. It was hitting that error when doing nested assign calls, like if you assign to an observable which triggers a computed that does another assign.

I just released v1.2.10 to fix it.

This is a test that reproduces the bug:

```js
test('Nested assign', () => {
    const obs = observable({ child: { a: 0, b: 0 } });
    const obs2 = observable({ child2: { a: 0, b: 0 } });
    const comp = computed(() => {
        const a = obs.child.a.get();

        obs2.child2.assign({ a: 2, b: 2 });

        return a;
    });

    comp.get();

    obs.child.assign({ a: 1, b: 1 });
});
```

Thanks for all the help with tracking it down ❤️

**Comment by devotox** [comment] 2023-06-18 09:14
@jmeistrich no thank you for taking the time and i know it was not straight forward since i could not get something reproducible. 🙏🏾

**Comment by devotox** [comment] 2023-06-18 22:50
@jmeistrich it seems to still be happening

```
{"message":"Error in TestModel observable assign: 'set' on proxy: trap returned falsish for property 'infiniteData' in TestModel Model","stack":"TypeError: 'set' on proxy: trap returned falsish for property 'infiniteData'\n   
   at Function.assign (<anonymous> undefined)\n   
   at assign .assign (/Users/devonte/Documents/Shares/shares/projects/app/node_modules/src/observable.ts:570:16 undefined)\n   
   at Proxy.<anonymous> (/Users/devonte/Documents/Shares/shares/projects/app/node_modules/src/observable.ts:337:32 undefined)\n   
   at TestModel.assign [as assignResponse] (/Users/devonte/Documents/Shares/shares/projects/app/src/api/models/Model.ts:783:23 undefined)\n   
   at Immediate.assignResponse [as _onImmediate] (/Users/devonte/Documents/Shares/shares/projects/app/src/api/models/Model.ts:757:14 undefined)\n   
   at processImmediate .processImmediate (node:internal/timers:471:21 undefined)","observableDiff":{"added":{},"deleted":{},"updated":{"data":[{"id":1}],"isSuccess":true,"isLoading":false,"isFetched":true,"dataUpdatedAt":1687128389407}}
```

**Comment by jmeistrich** [comment] 2023-06-18 23:14
Is it logging the new warning message "Error: Cannot set a value directly"?

Can you set a breakpoint inside proxyHandler.set and see which path it's going down? Where is it returning false?

**Comment by devotox** [comment] 2023-06-18 23:31
No its not logging that value and its the weirdest thing now. 


```
    const defaults = {
      data: undefined, // do not set data here as it will cause proxy trap error
      infiniteData: undefined, // do not set data here as it will cause proxy trap error
      infiniteDataPaged: undefined, // do not set data here as it will cause proxy trap error
      error: null,
      isStale: false,
      isError: false,
      isPaused: false,
      isSuccess: false,
      isLoading: false,
      isFetched: false,
      isFetching: false,
      isRefetching: false,
      dataUpdatedAt: null,
      hasNextPage: false,
      hasPreviousPage: false,
      isFetchingNextPage: false,
      isFetchingPreviousPage: false,
	
     // these are functions
      refetch: noop,
      reset: noopSync,
      remove: noopSync,
      fetchNextPage: noop,
      fetchPreviousPage: noop,
    };
```


setting the initial data like this causes an error but 

moving data, infiniteData, and infiniteDataPaged to the bottom below the functions and the error is gone. Might be a timing thing but maybe assigning when functions are involved also has some issues

**Comment by devotox** [comment] 2023-06-19 00:06
I have not been able to set a debug point since ts-node has issues currently with node 18 or something and it continuously gives me this error when i try to run it directly

```
/Users/devonte/Documents/Shares/shares/projects/app/node_modules/react-native-config/index.js:6
import { NativeModules } from 'react-native';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by devotox** [comment] 2023-06-19 15:57
Hey @jmeistrich i got the warning you said

```
 WARN  [legend-state]: Error: Cannot set a value directly: infiniteData undefined
 WARN  Proxy trap returned false for property in Contacts Model
 LOG  [Analytics event] error {"message":"Error in Contacts observable assign: Proxy trap returned false for property in Contacts Model","stack":"TypeError: Proxy trap returned false for property\n   
   at assign .assign (native undefined)\n   
   at assign .assign (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.shares.app.dev:181055:20 undefined)\n   
   at anonymous .anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.shares.app.dev:180885:24 undefined)\n   
   at assignResponse .assignResponse (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.shares.app.dev:190154:33 undefined)\n   
   at anonymous .anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.shares.app.dev:190139:34 undefined)\n   
   at apply .apply (native undefined)\n   
   at anonymous .anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.shares.app.dev:29871:26 undefined)\n   
   at _callTimer ._callTimer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.shares.app.dev:29790:17 undefined)\n   
   at _callReactNativeMicrotasksPass ._callReactNativeMicrotasksPass (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.shares.app.dev:29820:17 undefined)\n   
   at callReactNativeMicrotasks .callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.shares.app.dev:29983:44 undefined)\n   
   at __callReactNativeMicrotasks .__callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.shares.app.dev:2830:46 undefined)\n   
   at anonymous .anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.shares.app.dev:2642:45 undefined)\n   
   at __guard .__guard (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.shares.app.dev:2814:15 undefined)\n   
   at flushedQueue .flushedQueue (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.shares.app.dev:2641:21 undefined)\n   
   at callFunctionReturnFlushedQueue .callFunctionReturnFlushedQueue (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.shares.app.dev:2626:33 undefined)","observableDiff":{"added":{},"deleted":{},"updated":{"isSuccess":true,"isLoading":false,"isFetched":true,"isFetching":false,"dataUpdatedAt":1687190156306,"data":{"recommendations":[{"friend_id":110402,"display_name":"Adrian Seven","username":"seven","profile_pic":"https://dev-shares-bucket-public.s3.eu-west-3.amazonaws.com/dev/profile_pic/d8d4f465984556a43192088cb6844254-110402-1654511300270.jpeg","origin":"friends_of_friends","n_mutual":8,"mutual_friends":[157272,101232,136232,159723,99576,122239,140788,138631]},{"friend_id":99588,"display_name":"Duck","username":"crazyduck","profile_pic":"https://dev-shares-bucket-public.s3.eu-west-3.amazonaws.com/dev/profile_pic/fca068a38f2793d1fcd335700b451a2d-99588-1657707551636.jpeg","origin":"friends_of_friends","n_mutual":8,"mutual_friends":[157272,101232,144828,136232,159723,99576,122239,140788]},{"friend_id":110404,"display_name":"Adrian Threeone","username":"adrian_31","profile_pic":"https://dev-shares-bucket-public.s3.eu-west-3.amazonaws.com/dev/profile_pic/c96e2166d723fa5c68225995b2d227f4-110404-1656334950552.jpeg","origin":"friends_of_friends","n_mutual":7,"mutual_friends":[157272,136232,159723,99576,122239,140788,138631]},{"friend_id":110468,"display_name":"Ericcccccc","username":"eric","profile_pic":null,"origin":"friends_of_friends","n_mutual":7,"mutual_friends":[136232,159723,99576,163449,122239,140788,138631]},{"friend_id":110729,"display_name":"Caleb S","username":"caleb_s","profile_pic":null,"origin":"friends_of_friends","n_mutual":6,"mutual_friends":[157272,101232,144828,136232,122239,140788]},{"friend_id":110773,"display_name":"Jacques Selair","username":"jxlr","profile_pic":"https://dev-shares-bucket-public.s3.eu-west-3.amazonaws.com/dev/profile_pic/38e6d4c5c3c35b41ef9ab41aad9f315c-110773-1659953118769.jpeg","origin":"friends_of_friends","n_mutual":6,"mutual_friends":[101232,144828,136232,99576,140788,138631]},{"friend_id":128466,"display_name":"Vadko","username":"vadko","profile_pic":"https://dev-shares-bucket-public.s3.eu-west-3.amazonaws.com/dev/profile_pic/061b1b4fd5f82c3c46f91f21c9ab2459-128466-1668020330188.jpeg","origin":"friends_of_friends","n_mutual":6,"mutual_friends":[110872,157272,136232,119099,140788,138631]},{"friend_id":134626,"display_name":"Adrian Doe","username":"adrian_996","profile_pic":"https://dev-shares-bucket-public.s3.eu-west-3.amazonaws.com/dev/profile_pic/be248e45f4549e9c64f93b8654a91daa-134626-1655892496729.jpeg","origin":"friends_of_friends","n_mutual":5,"mutual_friends":[101232,136232,122239,140788,138631]},{"friend_id":110551,"display_name":"Anna Kucherov","username":"annakuch","profile_pic":"https://dev-shares-bucket-public.s3.eu-west-3.amazonaws.com/dev/profile_pic/7688302ea4187cd48e10e30562bd299b-110551-1649877913592.jpeg","origin":"friends_of_friends","n_mutual":5,"mutual_friends":[136232,99576,332130,122239,140788]},{"friend_id":136227,"display_name":"fruty aka","username":"b27ab08ceb","profile_pic":null,"origin":"friends_of_friends","n_mutual":5,"mutual_friends":[101232,136232,99576,122239,140788]},{"friend_id":136239,"display_name":"fruty aka","username":"62f8d20cb7","profile_pic":null,"origin":"friends_of_friends","n_mutual":5,"mutual_friends":[101232,136232,99576,122239,140788]},{"friend_id":136229,"display_name":"fruty aka","username":"7bac0f26ec","profile_pic":null,"origin":"friends_of_friends","n_mutual":5,"mutual_friends":[101232,136232,99576,122239,140788]},{"friend_id":350634,"display_name":"fruty testtesttesttesttes","username":"36242fab05","profile_pic":"https://dev-shares-bucket-public.s3.eu-west-3.amazonaws.com/dev/profile_pic/6eaa7643bd2305ab93a83b0b293545c5-350634-1683229622381.jpeg","origin":"friends_of_friends","n_mutual":5,"mutual_friends":[144828,99576,332130,122239,138631]},{"friend_id":215610,"display_name":"G rAlt","username":"g_ralt","profile_pic":"https://dev-shares-bucket-public.s3.eu-west-3.amazonaws.com/dev/profile_pic/14048994477957b1b3688b14e0ba1e7d-215610-1671535244760.jpeg","origin":"friends_of_friends","n_mutual":5,"mutual_friends":[157272,144828,159723,99576,332130]},{"friend_id":120169,"display_name":"Lorenz Henk","username":"lorenz","profile_pic":"https://dev-shares-bucket-public.s3.eu-west-3.amazonaws.com/dev/profile_pic/6d06ed19284c2bcdd4e61228551b5036-120169-1677062751647.jpeg","origin":"friends_of_friends","n_mutual":5,"mutual_friends":[144828,136232,332130,140788,138631]},{"friend_id":120134,"display_name":"Lui","username":"serra","profile_pic":null,"origin":"friends_of_friends","n_mutual":5,"mutual_friends":[144828,136232,159723,99576,122239]},{"friend_id":339741,"display_name":"Test testjdjdjddjdjdjdjdj","username":"testfollowolya","profile_pic":"https://dev-shares-bucket-public.s3.eu-west-3.amazonaws.com/dev/profile_pic/ea6222e5fbf4370def2915c3b8f34a26-339741-1678451755339.jpeg","origin":"friends_of_friends","n_mutual":5,"mutual_friends":[144828,159723,99576,332130,122239]},{"friend_id":136230,"display_name":"Adrian Fivehundred","username":"adrian_500","profile_pic":"https://dev-shares-bucket-public.s3.eu-west-3.amazonaws.com/dev/profile_pic/b3c8a786180720293b3e22d2fb71ae1b-136230-1656334823963.jpeg","origin":"friends_of_friends","n_mutual":4,"mutual_friends":[101232,136232,122239,140788]},{"friend_id":126521,"display_name":"Adrian Ninenineeight","username":"adrian_998","profile_pic":"https://dev-shares-bucket-public.s3.eu-west-3.amazonaws.com/dev/profile_pic/7b0f35850ef9b48e222320bf0f0453cc-126521-1666187712006.jpeg","origin":"friends_of_friends","n_mutual":4,"mutual_friends":[101232,136232,99576,140788]},{"friend_id":113247,"display_name":"Artur Two","username":"arturtwo","profile_pic":null,"origin":"friends_of_friends","n_mutual":4,"mutual_friends":[136232,99576,122239,140788]},{"friend_id":188574,"display_name":"Caleb Rock","username":"crock","profile_pic":"https://dev-shares-bucket-public.s3.eu-west-3.amazonaws.com/dev/profile_pic/c92b053ebcdf7622daaef251380a9a65-188574-1679044016282.jpeg","origin":"friends_of_friends","n_mutual":4,"mutual_friends":[101232,144828,159723,122239]},{"friend_id":348421,"display_name":"fruty aka","username":"e31625c113","profile_pic":"https://dev-shares-bucket-public.s3.eu-west-3.amazonaws.com/dev/profile_pic/890dcc75e2a2eb6cf2b837817a5c24c5-348421-1682220666216.jpeg","origin":"friends_of_friends","n_mutual":4,"mutual_friends":[157272,99576,332130,138631]},{"friend_id":261901,"display_name":"Ggjjgjg","username":"jgvjvj","profile_pic":null,"origin":"friends_of_friends","n_mutual":4,"mutual_friends":[157272,144828,159723,99576]},{"friend_id":277955,"display_name":"Gym Hut","username":"gjgjjgjv","profile_pic":null,"origin":"friends_of_friends","n_mutual":4,"mutual_friends":[157272,144828,159723,99576]},{"friend_id":115649,"display_name":"Lisa-lou","username":"llk","profile_pic":null,"origin":"friends_of_friends","n_mutual":4,"mutual_friends":[136232,159723,122239,140788]},{"friend_id":354897,"display_name":"Test            Test","username":"checkchatamb","profile_pic":"https://dev-shares-bucket-public.s3.eu-west-3.amazonaws.com/dev/profile_pic/f6120b3fa856b9400e1f35411a217eba-354897-1685025371109.jpeg","origin":"friends_of_friends","n_mutual":4,"mutual_friends":[157272,144828,122239,138631]},{"friend_id":244900,"display_name":"Wojtek","username":"wojtekpl","profile_pic":"https://dev-shares-bucket-public.s3.eu-west-3.amazonaws.com/dev/profile_pic/6a3a2536121bd14d2ac350a64e6f3586-244900-1668686254050.jpeg","origin":"friends_of_friends","n_mutual":4,"mutual_friends":[157272,144828,159723,99576]},{"friend_id":110552,"display_name":"Ania Khelaf","username":"aniakhe","profile_pic":"https://dev-shares-bucket-public.s3.eu-west-3.amazonaws.com/dev/profile_pic/906611882f76c55b41720418a0a62524-110552-1649877913645.jpeg","origin":"friends_of_friends","n_mutual":3,"mutual_friends":[144828,136232,140788]},{"friend_id":270854,"display_name":"Anna","username":"anna","profile_pic":null,"origin":"friends_of_friends","n_mutual":3,"mutual_friends":[157272,144828,99576]},{"friend_id":134666,"display_name":"Arian New","username":"adrian_889","profile_pic":null,"origin":"friends_of_friends","n_mutual":3,"mutual_friends":[101232,136232,140788]}],"contacts":[]}}}}


Formatted by https://st.elmah.io
```

**Comment by devotox** [comment] 2023-06-19 16:34
```
 WARN  [legend-state]: Error: Cannot set a value directly: isFetched true
```

**Comment by devotox** [comment] 2023-06-20 11:27
also just as an FYI literally adding a debounce / setImmediate before the assign and the issue is gone

**Comment by jmeistrich** [comment] 2023-06-20 18:22
@devotox Did v1.2.11 fix it?

**Comment by devotox** [comment] 2023-06-21 08:49
Will be testing it more today but I did not have the issue at all yesterday. I tried to revert back to some old code where i believe the issue was prevalent and it seemed to work as well. But i will have time to actually do some real systematic testing

**Comment by devotox** [comment] 2023-06-22 15:16
So it seems that for the usecases that I had I am no longer seeing the issue. Thank you 🙏🏾

**Comment by jmeistrich** [comment] 2023-06-22 21:32
Great! Let me know if you do encounter it again, but theoretically that should solve it. Thanks for all the help!

**Closed by jmeistrich** 2023-06-22 21:32 UTC

**Comment by SebastianDarie** [comment] 2023-11-09 14:27
If I have a structure like this 
```
type SelectedTicketStore = {
  new_message: ObservableObject<Partial<Message>>;
  ticket_messages?: Message[];
};

const selected_ticket$ = observable<SelectedTicketStore>({
  new_message: observable({
    id: '',
    content: '',
    created_at: new Date(),
    author_id: '',
  }),
  ticket_messages: [],
});
```
and then do something like this
```
<Reactive.input
          $value={selected_ticket$.new_message.content}
          onChange={(e) =>
            // selected_ticket$.new_message.content.set(e.target.value)
            selected_ticket$.new_message.assign({ content: e.target.value })
          }
/>
```
I get these
<img width="586" alt="image" src="https://github.com/LegendApp/legend-state/assets/47271657/ed1b0a0e-93fe-411b-9feb-c88b537e20a0">

If I delete the assign line and uncomment the explicit set on the content it works fine

**Comment by jmeistrich** [comment] 2023-11-09 15:48
The problem is that you're making new_message an observable inside of the selected_ticket$ observable. Everything inside of an observable is already an observable, so you can just take that out.

```js
type SelectedTicketStore = {
  new_message: ObservableObject<Partial<Message>>;
  ticket_messages?: Message[];
};

const selected_ticket$ = observable<SelectedTicketStore>({
  new_message: {
    id: '',
    content: '',
    created_at: new Date(),
    author_id: '',
  },
  ticket_messages: [],
});
```

**Comment by SebastianDarie** [comment] 2023-11-09 16:00
Yeah thought about that, I'm just not sure what is the legend way to approaching mobx-state-tree like models where I could have basically `new_message` as an observable with its own methods and computed fns inside the main store or like an array of messages which also have their own methods with them
Is there a suggested approach for this or just keeping it as simple objects and having the methods as external functions in separate files?

**Comment by jmeistrich** [comment] 2023-11-09 16:11
You can put functions in observables. Can you show me how you're trying to use functions that's not working?

**Comment by SebastianDarie** [comment] 2023-11-09 16:20
let's say I want a method isValid on new_message I can add it like this
```
isValid() {
            const uploadAttachmentError = _.find(selected_ticket$?.upload_attachments.get(true), {
                upload_file_error: true,
            })

            if (uploadAttachmentError) return false

            const regExp = new RegExp(/<div>|<\/div>|<br>|&nbsp;/gim)
            const validateContentForEmpty = this?.content?.replace(regExp, '')

            if (validateContentForEmpty?.trim().length || selected_ticket$?.upload_attachments.get(true).length)
                return true

            return false
        },
```
then it's a simple function but I would like to make it as a computed just like I can in the selected_ticket store and computed callbacks don't have a this with the current object or observable
