### ISSUE TITLE
Attempted import error: 'useSelector' is not exported from '@legendapp/state/react' (imported as 'useSelector').

### ISSUE THREAD

**Issue by tendertree** [LegendApp/legend-state#222] opened 2023-11-10 13:25 UTC
Attempted import error: 'useSelector' is not exported from '@legendapp/state/react' (imported as 'useSelector')

```
import { observable } from "@legendapp/state";
import { enableReactTracking } from "@legendapp/state/config/enableReactTracking";

enableReactTracking({
	auto: true,
});
const name$ = observable({ name: "kim", age: 5 });
export default function Home() {
	const name = name$.name.get();
	return (
		<div> {name} </div>
	)
}
```
I try to add 

```
import { useSelector } from "@legendapp/state/react"
```

but error still show 

currently  "@legendapp/state": "^2.1.2" is installed

**Comment by jmeistrich** [comment] 2023-11-10 15:04
Is this in Next.js 14? Maybe it's the same cause as https://github.com/LegendApp/legend-state/issues/221?

**Comment by jmeistrich** [comment] 2023-11-10 16:42
I tried updating to Next.js 14 and couldn't reproduce any problems. Could you tell me more about your environment? Was it working before you changed something?

**Comment by michaelzadra1** [comment] 2023-11-10 20:28
For me, this is easily reproducible by upgrading Next from version 14.0.1, to 14.0.2

**Comment by jmeistrich** [comment] 2023-11-10 21:46
It seems to be caused by https://github.com/vercel/next.js/pull/57784 and some others are reporting the same issue. I'll investigate further, but for now I guess stay on 14.0.1?

I guess it's not breaking for my tests because we use SSG and it's an SSR specific issue?

**Comment by tendertree** [comment] 2023-11-11 03:14
try to change next versioon 14.0.1 issue happend again 

"@legendapp/state": "^2.1.3",
 "next": "14.0.2",
```
./node_modules/.pnpm/@legendapp+state@2.1.3_react@18.2.0/node_modules/@legendapp/state/config/enableReactTracking.mjs
Attempted import error: 'useSelector' is not exported from '@legendapp/state/react' (imported as 'useSelector').
```

source code is here
https://github.com/tendertree/nextWithlegend

**Comment by Tekutorukushi** [comment] 2023-11-14 11:32
Any solutions? We need something to work with NextJs 14.0.2

**Comment by jmeistrich** [comment] 2023-11-14 14:08
I'm not sure what the problem even is so I'm not sure how to solve it. It seems to be a bug in Next because it works in every other environment and it's worked in Next up until the update broke it. Multiple packages seem to be having the same problem so I think it's not a legend-state bug?

Can you try posting an issue in the Next.js repo? Or if you can track down the issue and attempt a fix or guide me on where to start, it would be a huge help.

**Comment by jacktsin1** [comment] 2023-11-19 04:42
Same here, I'm getting similar errors:
`Attempted import error: 'Show' is not exported from '@legendapp/state/react' (imported as 'Show').`
`Attempted import error: 'useSelector' is not exported from '@legendapp/state/react' (imported as 'useSelector').`

**Comment by DawidWraga** [comment] 2023-12-04 19:36
any updates on this?

**Comment by jmeistrich** [comment] 2023-12-04 20:50
Some say it may be fixed in the next update, which would be 14.0.4. I've never reproduced it myself so I'm not 100% sure if their fix will actually fix this.

**Comment by Tekutorukushi** [comment] 2023-12-07 08:48
I checked it on v14.0.4-canary.44, it was fixed, now everything works for me.

**Comment by mariuszubryt** [comment] 2023-12-08 12:21
I can confirm that upgrading Next to `14.0.4` solved the same error for us during the build process.

**Closed** 2024-05-22 19:52 UTC
