### ISSUE TITLE
Recommandations in Notes (in Docs v3) break re-rendering

### ISSUE THREAD

**Issue by mkhennoussi** [LegendApp/legend-state#321] opened 2024-06-29 11:07 UTC
Hi there ! Hope you are doing well guys !

I have noticed some issues by using some informations in the new docs : 

`// ✅ Just push it
list$.push('value')
` or 
`// ✅ Delete it from the array directly
const list = list$.get()
const idx = list.findIndex((item) => item.id === itemId)
list$[idx].delete()
`

For instance if you have an array of items, you push new items to it, then you delete these items, then you push new items again  => it breaks the re-rendering of the list (using both the <For> component ou the arr.map function) so you have to click multiple times to "force" the re-rendering.

This issue doesn't exist when we clone the object (like we are used to do in React). 

Have a look at this example : https://stackblitz.com/edit/vitejs-vite-if1btp?file=src%2Fstore.ts,src%2FApp.tsx&terminal=dev

Click on "Create an estimation" then delete this estimation by clicking on "Delete", then click again on "Create an estimation" => The second estimation is not rendered. If you click a third time on "Create an estimation" you will see both, the 2nd and the 3rd estimation rendered. 

Thanks for you help !

**Comment by jmeistrich** [comment] 2024-06-30 02:41
Thanks for the report! I've reproduced it in a test and I'm working on a fix.

**Comment by jmeistrich** [comment] 2024-07-01 01:05
Should be fixed in alpha.19. I updated a fork of that stackblitz and it looks like it works correctly now. So I'll close the issue but please let me know if it's still not quite right.

**Closed by jmeistrich** 2024-07-01 01:05 UTC
