### ISSUE TITLE
useObservable when given a function seems to update function references on rerenders

### ISSUE THREAD

**Issue by briandipalma** [LegendApp/legend-state#228] opened 2023-11-23 12:36 UTC
```typescript
const store = useObservable({
  myFunction: () => {},
  primitiveData: "Hi!",
})
```

Rerendering this I wouldn't expect myFunction to update but it does...it acts differently to how useState would act. I see there is some value in this but it's causing useEffects to trigger that shouldn't. I'd only expect the function reference to update when I perform an assign on the store.

**Comment by briandipalma** [comment] 2023-11-23 12:52
OK so the issue is that the Proxy reference doesn't equal the original function reference I'm guessing? Because what I'm seeing debugging this issue is totally bonkers. It looks like `===` is broken for functions inside observables because I guess the equals trap isn't checking the underlying functions for equality but the Proxy wrapper which I guess is different on each render?

**Comment by jmeistrich** [comment] 2023-11-23 14:19
Can you share more of the code where you're doing the comparison? I'm not sure from your description what the issue is. What is the reason that you need to compare functions?

Legend-State extracts functions off of the raw object so depending on how you're doing the comparison the functions may not actually be there at all. It does that so that setting an object later doesn't remove any functions that were there. And an upcoming version is going to use inline functions as a way to do observables (though normal functions will still work) and that also needs to remove them from the actual object.

**Comment by briandipalma** [comment] 2023-12-20 17:36
Here's some simple code which show the issue: https://codesandbox.io/p/sandbox/legend-state-228-m4vv9m?file=%2Fsrc%2FApp.tsx%3A14%2C23

This is an infinite loop BTW. Change `[store.myFunction]` to `[store.primitiveData]` and the infinite loop is fixed. This seems like a bug to me?

**Comment by jmeistrich** [comment] 2024-05-22 19:51
I think this should be fixed in version 3 alpha. Can you try updating to the latest `@alpha` version and see if it’s fixed?

**Closed by jmeistrich** 2024-05-22 19:51 UTC

**Comment by briandipalma** [comment] 2024-05-24 12:08
The sandbox issue seems fixed with the latest alpha https://codesandbox.io/p/sandbox/legend-state-228-m4vv9m?file=%2Fsrc%2FApp.tsx%3A2%2C45
