### ISSUE TITLE
Something broken in react-native-web?

### ISSUE THREAD

**Issue by djMax** [LegendApp/legend-state#98] opened 2023-02-11 21:59 UTC
I'm working to isolate, but right now I have the world's simplest observable hooked up to a switch in react-native-elements. It works fine in ios/android but simply doesn't cause a re-render on web. Additionally, adding useTraceListeners and useTraceUpdates prints nothing on the web - not even the first render. I've put console.logs there to prove I'm visiting the right code, but it just doesn't do anything, doesn't print any error... nothing.

Any ideas what to look at next?

**Comment by djMax** [comment] 2023-02-11 22:33
Here is one diff between web and not web: 
```
  config.module.rules.push(
    {
      test: /\.mjs$/,
      exclude: [/node_modules\/@legendapp\/state\/persist-plugins\/mmkv/],
    },
    {
      test: /\.mjs$/,
      include: /node_modules\/@legendapp/,
      type: 'javascript/auto',
    },
  );
```

**Comment by djMax** [comment] 2023-02-11 22:47
```
import { observable } from '@legendapp/state';
import { observer } from '@legendapp/state/react';

const CounterState = observable({ count: 1 });
const CounterValue = observer(() => <Text>{CounterState.count.get()}</Text>);

function MyComponent() {
  setInterval(() => {
    console.log('Add', CounterState.count.peek());
    CounterState.count.set(CounterState.count.peek() + 1);
  }, 1000);

  return <CounterValue />
}
```

That does not update.

**Comment by jmeistrich** [comment] 2023-02-12 00:10
Can you try the latest RC version and see if it works better? `npm install @legendapp/state@rc`

Or is it possible to share a repo that I can test with? We have a react-native-web project that works fine and I don't see any obvious problems from this code, so it would be great to be able to debug through it. And it may be that different versions of react-native-web work in different ways. I think our project is still on version 17.

**Comment by djMax** [comment] 2023-02-12 00:27
I added you to the repo (infinitesimal-chess).

**Comment by jmeistrich** [comment] 2023-02-12 01:30
I see the problem but I'm not sure how to fix it, and working on figuring that out.

The problem is that it is importing index.mjs and react.mjs, but then react.mjs imports index.js. So it's running two different instances of Legend-State, and that's why it's not working. I'll hopefully figure this out shortly! Let me know if you know how to solve it :)

**Comment by djMax** [comment] 2023-02-12 01:33
That's exactly what I was afraid of with the webpack hijinx, but I couldn't figure out why it would've just started. When I was originally trying to get it to work, I removed all the mjs files and updated package.json to point to the js one, and then yarn must not have undone that change through all the weeks of messing about with deps. But yesterday I tried to upgrade Expo (and then backed out) and I bet it reset that patch.

At least I can push a fix to the website while we sort it out. :) Thank you very much for digging.

**Comment by djMax** [comment] 2023-02-12 01:35
This also explains why building and deploying from github actions was failing! No patch.

**Comment by jmeistrich** [comment] 2023-02-12 01:44
Ok, if you've got a temporary solution then I'll focus on finding a longterm solution to this. I had trouble finding the right way to package all the different types of exports, but I'll try again now and see if I can find an "official" best practice.

**Comment by djMax** [comment] 2023-02-12 01:46
Yeah, I reiterate my strong belief that ESM is the biggest threat to the javascript ecosystem since Internet Explorer.

**Comment by jmeistrich** [comment] 2024-06-01 02:29
I believe this is fixed now so I’m going to close it, but please let me know if it’s still an issue.

**Closed by jmeistrich** 2024-06-01 02:29 UTC
