### ISSUE TITLE
crud plugin: onSaved not firing

### ISSUE THREAD

**Issue by mdj-uk** [LegendApp/legend-state#349] opened 2024-08-17 21:31 UTC
In 3.0.0-alpha.29, the `onSaved` callback for the crud plugin doesn't seem to fire.

See [codesandbox](https://codesandbox.io/p/sandbox/legend-demo-forked-27ly64?workspaceId=ae337f1b-328d-4680-9ae3-00c199f29fea&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzlty6dd00063b6i88gxoroj%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzlty6dc00023b6iapcenfgt%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzlty6dc00033b6ipauir0jr%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzlty6dc00053b6iuwc0pw5y%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzlty6dc00023b6iapcenfgt%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzlty6dc00013b6i2k97xw57%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzo7fl7q00023b6ixf7c8vvj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FlegendStore.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzo8hnig00023b6ib0agq2lf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A26%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A26%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzo8twt200023b6ijgwsa8uh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A61%252C%2522startColumn%2522%253A49%252C%2522endLineNumber%2522%253A61%252C%2522endColumn%2522%253A49%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FlegendSync.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzymi2xg00023b6icrcil7uz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A15%252C%2522startColumn%2522%253A11%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A11%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FlegendSyncComponent.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzlty6dc00023b6iapcenfgt%2522%252C%2522activeTabId%2522%253A%2522clzymi2xg00023b6icrcil7uz%2522%257D%252C%2522clzlty6dc00053b6iuwc0pw5y%2522%253A%257B%2522id%2522%253A%2522clzlty6dc00053b6iuwc0pw5y%2522%252C%2522activeTabId%2522%253A%2522clzymvesh00243b6i89hlbsne%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzlty6dc00043b6izijzt1ht%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clzltz3ec001d3b6ijwakgkjg%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clzymvesh00243b6i89hlbsne%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzlty6dc00033b6ipauir0jr%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzlty6dc00033b6ipauir0jr%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D). Note that on adding item to todo list the console log from `create` appears, but not the one from `onSaved`

**Comment by jmeistrich** [comment] 2024-09-18 21:09
Thanks @mdj-uk and sorry for the delay! It seems to be an issue with `as: "array"`. I've reproduced it and will try to fix it.

**Comment by jmeistrich** [comment] 2024-09-19 09:03
This is fixed in alpha.40. Thanks for the report!

**Closed by jmeistrich** 2024-09-19 09:03 UTC

**Comment by mdj-uk** [comment] 2024-09-20 21:47
Thanks!
