### ISSUE TITLE
Sometimes `when` is not triggered

### ISSUE THREAD

**Issue by hckhanh** [LegendApp/legend-state#51] opened 2022-10-28 03:01 UTC
Sometimes, when I try to navigate between my routes, the state changes but the `when` function is not triggered. I am using react-location (Data API). Now I have to switch to `authorization.state.onChange`

```tsx
when(
  () => authorization.state.get() === 'unauthorized',
  () => {
    import('@/utils/modal').then(({ showLoginModal }) => {
      showLoginModal()
    })
  }
)

when(
  () => authorization.state.get() === 'anonymous',
  () => {
    console.log('logout')
    if (history.location.pathname.includes('/dashboard')) {
      history.push(
        {
          pathname: '/login',
          search: `?redirect=${encodeURIComponent(
            `${history.location.pathname}${history.location.search}`
          )}`,
        },
        history.location.state
      )
    }
  }
)
```

**Comment by hckhanh** [comment] 2022-10-28 03:02
I will come up with demo later.

**Comment by jmeistrich** [comment] 2022-10-28 05:07
`when` can be a bit confusing because it only triggers once. Once it's triggered it disposes its listeners. Is that the issue that you're seeing? If so you may be better off using `observe` to trigger whenever it changes, so this example using `observe` could look like:

```js
observe(() => {
  const authState = authorization.state.get()
  if (authState === 'unauthorized') {
    import('@/utils/modal').then(({ showLoginModal }) => {
      showLoginModal()
    })
  }
  else if (authState === 'anonymous') {
    console.log('logout')
    if (history.location.pathname.includes('/dashboard')) {
      history.push(
        {
          pathname: '/login',
          search: `?redirect=${encodeURIComponent(
            `${history.location.pathname}${history.location.search}`
          )}`,
        },
        history.location.state
      )
    }
  }
})
```

Or if that's not the problem, a demo will be very helpful to track it down 😎

**Comment by hckhanh** [comment] 2022-10-29 10:35
Hi @jmeistrich, here is my full implementation with `when`:

```tsx
import { history } from '@/utils/location'
import { observable, when } from '@legendapp/state'
import { ObservablePersistLocalStorage } from '@legendapp/state/local-storage'
import { persistObservable } from '@legendapp/state/persist'

export const authorization = observable<{
  token: string
  state: 'anonymous' | 'login' | 'unauthorized'
}>({ token: '', state: 'anonymous' })

// Load token from local storage
when(authorization.token, () => {
  authorization.state.set('login')
})

when(
  () => authorization.state.get() === 'anonymous',
  () => {
    if (history.location.pathname.includes('/dashboard')) {
      history.push(
        {
          pathname: '/login',
          search: `?redirect=${encodeURIComponent(
            `${history.location.pathname}${history.location.search}`
          )}`,
        },
        history.location.state
      )
    }
  }
)

when(
  () => authorization.state.get() === 'unauthorized',
  () => {
    import('@/utils/modal').then(({ showLoginModal }) => {
      showLoginModal()
    })
  }
)

persistObservable(authorization.token, {
  local: 'authorization',
  persistLocal: ObservablePersistLocalStorage,
})
```
I forgot to tell you I persisted the observable before the `when` is loaded.
Now It works as I expected after I move the `persistObservable` to the bottom, to make sure the `when` statements are loaded before persisting the state.

**Comment by jmeistrich** [comment] 2022-10-29 14:07
@hckhanh Was there a bug in `when` if it's in a different order? Or does it just need to be documented better?

**Comment by hckhanh** [comment] 2022-10-30 00:17
@jmeistrich, I had a problem with the order of `persistObservable`. For `when`, i think that it should be documented better to make it less confusing.

**Comment by jmeistrich** [comment] 2022-10-30 03:28
@hckhanh If there's a bug when using `persistObservable` and `when` in a different order, we should fix that. Can you share an example of it not working?

**Comment by hckhanh** [comment] 2022-10-30 05:53
@jmeistrich, I try to reproduce but I did not see any problems.
Maybe I get that weird issue with HRM when I run with Vite in development mode.

https://codesandbox.io/s/jovial-star-dg2hho?file=/src/App.js

```
[legend-state]: Called persist with the same local name multiple times: token
```

**Comment by jmeistrich** [comment] 2022-10-30 06:40
@hckhanh Ok great, I've added to my todo list to document when better, so I'll close this issue. If you reproduce a bug with this please let me know.

I get that warning with HMR too, but it's nothing to worry about. It's on my todo list to try to fix but it's not causing any issues as far as I can tell.

**Closed by jmeistrich** 2022-10-30 06:40 UTC

**Comment by hckhanh** [comment] 2022-10-30 06:42
@jmeistrich, I think that the order of `persistObservable`  and `observe` does matter.
You can follow my demo: https://codesandbox.io/s/jovial-star-dg2hho?file=/src/App.js

When I put `persistObservable` between `when` and `observe`. I will get this result:

```
load token 
login
```

But when I move `persistObservable` to the end of the initialization, I get this:

```
anonymous 
load token 
login 
```

**Comment by jmeistrich** [comment] 2022-10-30 08:54
@hckhanh Ah ok, I think that is the expected behavior. `persistObservable` loads the cached value into the observable immediately, so it's effectively the same as calling `state.token.set("tokenvalue")`.

So if you persist it before the `observe` then it will
1. call the `when` function as the token loads from persistence
2. create and run `observe`. 

But if you persist it after, then it 
1. runs `observe` immediately with the initial state of "anonymous"
2. runs `when` when the persisted token loads
3. runs `observe` again when you set the status inside `when`

I can definitely see how this is confusing! I'll take a look at improving the docs.
