### ISSUE TITLE
Optional/nullable properties don't infer types correctly

### ISSUE THREAD

**Issue by Pinpickle** [LegendApp/legend-state#151] opened 2023-07-21 07:04 UTC
Given my reading of the [docs](https://legendapp.com/open-source/state/observable/#undefined), having paths to access undefined/null values is valid.

However, this code gives TS errors, presumably because the presence of `undefined` and `null` types makes the type inference break. I have checked that this works as-expected at runtime.

```
const test = observable<{
  optional?: { foo: string };
  nullable: { foo: string } | null;
}>({
  optional: undefined,
  nullable: null,
});

test.optional.foo.set("baz");
// error: 'test.optional' is possibly 'undefined'.
// error: Property 'foo' does not exist on type 'ObservableObject<{ foo: string; } | undefined>'

test.nullable.foo.set("baz");
// error: Property 'foo' does not exist on type 'ObservableObject<{ foo: string; } | null>'
```

Is this expected behaviour? Are there any workarounds?

**Comment by jmeistrich** [comment] 2023-07-21 07:13
Oh interesting! The problem is the optional properties. I'll release a fix shortly that coerces observable types to remove optionality.

**Comment by jmeistrich** [comment] 2023-07-21 07:36
Fixed in v1.5.1. Thanks for catching that!

**Comment by Pinpickle** [comment] 2023-07-21 22:43
@jmeistrich thanks for the prompt fix! I can confirm the TS errors are gone.

However, we've lost a fair amount of null-safety in the process. Both of these examples typecheck correctly but throw errors at runtime due to `nullable` being set to `null`. I'd expect TS to remember the optional properties once they've been unwrapped with `get`.

```
const test = observable<{
  optional?: { foo: string };
  nullable: { foo: string } | null;
}>({
  optional: undefined,
  nullable: null,
});

test.nullable.foo.get().trim()
// Runtime: Cannot read properties of null (reading 'trim')
test.nullable.get().foo.trim()
// Runtime: Cannot read properties of null (reading 'foo')
```

Should I open a new issue for this?

**Comment by jmeistrich** [comment] 2023-07-22 09:19
@Pinpickle I think version 1.6.1 improves handling of undefined, but I haven't been able to figure out how to make the observable object non-null but keep the underlying as is. I'll reopen this issue to revisit that later. Or if you or any TS wizards can figure out how to make it work a PR would be great 😀

**Comment by baptisteArno** [comment] 2023-08-28 15:48
That definitely prevent me from adopting Legend at the moment! Are you working on this on the next v2 release?

Otherwise, I can take a look

**Comment by jmeistrich** [comment] 2023-08-28 18:47
@baptisteArno I have tried briefly a couple of times to improve it but I haven't had a lot of time to put into it, and it's not currently top of mind. The v2 release is going to be mainly about persistence features.

If you'd like to take a look it would be amazing! I would love to see this improved.

**Closed** 2023-09-19 12:06 UTC

**Comment by levic92** [comment] 2024-03-09 07:01
This seems to be an issue again in`"@legendapp/state": "^2.1.8"` 

Everything is getting typed as NonNullable

**Comment by jmeistrich** [comment] 2024-03-09 17:41
We've rewritten the types from scratch with @bram209's help in the @next version which should hopefully fix this. Can you try version @2.2.0-next.53 and see if that fixes the types for you? That will be turned into version 3.0, coming in a few weeks hopefully.

**Comment by levic92** [comment] 2024-03-09 18:46
With that version I now have the issue of anything returned by calling `.get()` is types as a generic `RemoveObservables<T>`

Example `const theme = settings$.theme.get();` is `RemoveObservables<T>`
However without the `.get()` call the type is `ObservablePrimitive<ColorSchemeName>`

**Comment by jmeistrich** [comment] 2024-03-09 18:59
@levic92 Can you share a larger example of an observable where the types are doing that?

**Comment by levic92** [comment] 2024-03-09 20:12
```
import type { ColorSchemeName } from "react-native";

import { observable } from "@legendapp/state";
import { persistObservable } from "@legendapp/state/persist";

type TSettings = {
  theme?: ColorSchemeName;
  contactInfo: {
    firstName?: string;
    lastName?: string;
    email?: string;
    phone?: string;
  };
};

export const settings$ = observable<TSettings>({ contactInfo: {} });

persistObservable(settings$, {
  local: "settings",
});

```
